repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: requirements-txt-fixer
#-   repo: https://github.com/psf/black
#    rev: 22.3.0
#    hooks:
#    id: black
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
    stages: [commit]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    additional_dependencies: [toml]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint-fix
    entry: markdownlint -f README.md --disable MD013 MD036
        # args: [--disable MD013 MD036]
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.3
  hooks:
  - id: nbqa-isort
  - id: nbqa-yapf
    additional_dependencies: [toml, yapf]
