name: csromer-env
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- numpy=1.23
- blas-devel
- libblas
- libcblas
- liblapack
- liblapacke
- anaconda
- pip
- pip:
  - astropy==5.1.0
  - astropy-healpix==0.6
  - astroquery==0.4.4
  - h5py==3.1.0
  - joblib==1.1.0
  - matplotlib==3.6.1
  - numpy==1.23.4
  - prox_tv==3.2.1
  - proxmin==0.6.11
  - pynufft==2022.2.3
  - PyWavelets==1.4.1
  - scipy==1.9.3
