[build-system]
requires = ["setuptools>=62.3.2", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "csromer"
description = "Compressed Sensing Rotation Measure Reconstructor"
readme = "README.md"
license = {text = "GNU GPL"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dynamic = ["version"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["csromer"]
namespaces = false

[tool.setuptools_scm]
write_to = "csromer/_version.py"
