# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: testpypi-publish

on:
  push:
    branches:
      - development
    paths:
      - 'setup.py'
  pull_request:
    branches:
      - master
    paths:
      - 'setup.py'


permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:base
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          set-safe-directory: true
      - name: Check git version and our path
        run: |
          git --version
          ls -lah
          ls -lah .git/
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip wheel setuptools
            python3 -m pip install virtualenv
            python3 -m pip install build
      - name: Build package
        run: python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
